FROM node:24-alpine

WORKDIR /app

# Install dependencies for the entire backend monorepo
COPY package*.json ./
RUN npm ci

# Copy backend sources (including prisma and apps)
COPY . .

CMD ["npm", "run", "start:user-service:dev"]