global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']
    metrics_path: '/metrics'

  # User Service metrics
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5000']
    metrics_path: '/metrics'

  # Inventory Service metrics
  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:5001']
    metrics_path: '/metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

